const OUTPUT_ARTIFACTS = Object.freeze({
  PRE_EVENT_RESULTS_JSON: 'PRE_EVENT_RESULTS_JSON',
  PRE_EVENT_RESULTS_TXT: 'PRE_EVENT_RESULTS_TXT',
  PRE_EVENT_RANKINGS_JSON: 'PRE_EVENT_RANKINGS_JSON',
  PRE_EVENT_RANKINGS_CSV: 'PRE_EVENT_RANKINGS_CSV',
  PRE_EVENT_SIGNAL_CONTRIBUTIONS_JSON: 'PRE_EVENT_SIGNAL_CONTRIBUTIONS_JSON',

  POST_EVENT_RESULTS_JSON: 'POST_EVENT_RESULTS_JSON',
  POST_EVENT_RESULTS_TXT: 'POST_EVENT_RESULTS_TXT',

  TOURNAMENT_RESULTS_JSON: 'TOURNAMENT_RESULTS_JSON',
  TOURNAMENT_RESULTS_CSV: 'TOURNAMENT_RESULTS_CSV',
  TOURNAMENT_RESULTS_ZSCORES_CSV: 'TOURNAMENT_RESULTS_ZSCORES_CSV',
  TOURNAMENT_RESULTS_FORMATTING_CSV: 'TOURNAMENT_RESULTS_FORMATTING_CSV',

  SEED_SUMMARY_TXT: 'SEED_SUMMARY_TXT',
  SEED_LOG_TXT: 'SEED_LOG_TXT',

  PRE_EVENT_LOG_TXT: 'PRE_EVENT_LOG_TXT',
  POST_EVENT_LOG_TXT: 'POST_EVENT_LOG_TXT',

  TOP20_TEMPLATE_BLEND_JSON: 'TOP20_TEMPLATE_BLEND_JSON',

  RAMP_JSON: 'RAMP_JSON',
  RAMP_CSV: 'RAMP_CSV',

  COURSE_HISTORY_REGRESSION_JSON: 'COURSE_HISTORY_REGRESSION_JSON',
  COURSE_HISTORY_REGRESSION_SUMMARY_CSV: 'COURSE_HISTORY_REGRESSION_SUMMARY_CSV',
  COURSE_HISTORY_REGRESSION_DETAILS_CSV: 'COURSE_HISTORY_REGRESSION_DETAILS_CSV',
  COURSE_HISTORY_REGRESSION_SUMMARY_SIMILAR_CSV: 'COURSE_HISTORY_REGRESSION_SUMMARY_SIMILAR_CSV',
  COURSE_HISTORY_REGRESSION_DETAILS_SIMILAR_CSV: 'COURSE_HISTORY_REGRESSION_DETAILS_SIMILAR_CSV',

  VALIDATION_CALIBRATION_REPORT_JSON: 'VALIDATION_CALIBRATION_REPORT_JSON',
  VALIDATION_CALIBRATION_REPORT_CSV: 'VALIDATION_CALIBRATION_REPORT_CSV',
  VALIDATION_COURSE_TYPE_CLASSIFICATION_JSON: 'VALIDATION_COURSE_TYPE_CLASSIFICATION_JSON',
  VALIDATION_COURSE_TYPE_CLASSIFICATION_CSV: 'VALIDATION_COURSE_TYPE_CLASSIFICATION_CSV',
  VALIDATION_WEIGHT_CALIBRATION_GUIDE_JSON: 'VALIDATION_WEIGHT_CALIBRATION_GUIDE_JSON',
  VALIDATION_WEIGHT_CALIBRATION_GUIDE_CSV: 'VALIDATION_WEIGHT_CALIBRATION_GUIDE_CSV',
  VALIDATION_WEIGHT_TEMPLATES_JSON: 'VALIDATION_WEIGHT_TEMPLATES_JSON',
  VALIDATION_WEIGHT_TEMPLATES_CSV: 'VALIDATION_WEIGHT_TEMPLATES_CSV',
  VALIDATION_MODEL_DELTA_TRENDS_JSON: 'VALIDATION_MODEL_DELTA_TRENDS_JSON',
  VALIDATION_MODEL_DELTA_TRENDS_CSV: 'VALIDATION_MODEL_DELTA_TRENDS_CSV',
  VALIDATION_PROCESSING_LOG_JSON: 'VALIDATION_PROCESSING_LOG_JSON',
  VALIDATION_METRIC_ANALYSIS_JSON: 'VALIDATION_METRIC_ANALYSIS_JSON',
  VALIDATION_METRIC_ANALYSIS_CSV: 'VALIDATION_METRIC_ANALYSIS_CSV',
  VALIDATION_TEMPLATE_CORRELATION_SUMMARY_JSON: 'VALIDATION_TEMPLATE_CORRELATION_SUMMARY_JSON',
  VALIDATION_TEMPLATE_CORRELATION_SUMMARY_CSV: 'VALIDATION_TEMPLATE_CORRELATION_SUMMARY_CSV',
  VALIDATION_SEASON_POST_EVENT_SUMMARY_JSON: 'VALIDATION_SEASON_POST_EVENT_SUMMARY_JSON',
  VALIDATION_SEASON_POST_EVENT_SUMMARY_CSV: 'VALIDATION_SEASON_POST_EVENT_SUMMARY_CSV',
  VALIDATION_SEASON_POST_EVENT_SUMMARY_MD: 'VALIDATION_SEASON_POST_EVENT_SUMMARY_MD'
});

const VALIDATION_SUBDIRS = Object.freeze({
  METRIC_ANALYSIS: 'metric_analysis',
  TEMPLATE_CORRELATION_SUMMARIES: 'template_correlation_summaries',
  TOP20_BLEND: 'top20_blend',
  SEASON_SUMMARIES: 'season_summaries'
});

module.exports = {
  OUTPUT_ARTIFACTS,
  VALIDATION_SUBDIRS
};
